OUTPUT_FORMAT("elf32-i386","elf32-i386","elf32-i386");
OUTPUT_ARCH("i386")

ENTRY(entry)

SECTIONS
{
   . = 0x200000;
   _c_start = .;

   .multiboot       . : { *(.multiboot) . = ALIGN(4);           }
   .text      . : { *(.text)                        }
   .rodata      : { *(.rodata)                      }
   .data        : { *(.data)                        }
   .bss         : { *(.bss COMMON)                  }
   /DISCARD/  	: { *(.note* .indent .comment)      }
}

